set_property CFGBVS GND [current_design]
set_property CONFIG_VOLTAGE 1.8 [current_design]
set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]

set_property PACKAGE_PIN G22 [get_ports {GPIO_LED[9]}]
set_property PACKAGE_PIN M24 [get_ports {GPIO_LED[8]}]
set_property PACKAGE_PIN E22 [get_ports {GPIO_LED[7]}]
set_property PACKAGE_PIN F22 [get_ports {GPIO_LED[6]}]
set_property PACKAGE_PIN B16 [get_ports {GPIO_LED[5]}]
set_property PACKAGE_PIN G19 [get_ports {GPIO_LED[4]}]
set_property PACKAGE_PIN AE15 [get_ports {GPIO_LED[3]}]
set_property PACKAGE_PIN W15 [get_ports {GPIO_LED[2]}]
set_property PACKAGE_PIN Y15 [get_ports {GPIO_LED[1]}]
set_property PACKAGE_PIN J15 [get_ports {GPIO_LED[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GPIO_LED[9]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GPIO_LED[8]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GPIO_LED[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GPIO_LED[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GPIO_LED[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GPIO_LED[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_LED[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_LED[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_LED[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_LED[0]}]
set_property PACKAGE_PIN AC14 [get_ports {GPIO_DIP_SW[7]}]
set_property PACKAGE_PIN AC13 [get_ports {GPIO_DIP_SW[6]}]
set_property PACKAGE_PIN AF15 [get_ports {GPIO_DIP_SW[5]}]
set_property PACKAGE_PIN AF14 [get_ports {GPIO_DIP_SW[4]}]
set_property PACKAGE_PIN G14 [get_ports {GPIO_DIP_SW[3]}]
set_property PACKAGE_PIN H14 [get_ports {GPIO_DIP_SW[2]}]
set_property PACKAGE_PIN W13 [get_ports {GPIO_DIP_SW[1]}]
set_property PACKAGE_PIN W12 [get_ports {GPIO_DIP_SW[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_DIP_SW[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_DIP_SW[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_DIP_SW[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_DIP_SW[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_DIP_SW[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_DIP_SW[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_DIP_SW[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_DIP_SW[0]}]

set_property PULLTYPE PULLDOWN [get_ports {GPIO_LED[0]}]
set_property PULLTYPE PULLDOWN [get_ports {GPIO_LED[1]}]
set_property PULLTYPE PULLDOWN [get_ports {GPIO_LED[2]}]
set_property PULLTYPE PULLDOWN [get_ports {GPIO_LED[3]}]
set_property PULLTYPE PULLDOWN [get_ports {GPIO_LED[4]}]
set_property PULLTYPE PULLDOWN [get_ports {GPIO_LED[5]}]
set_property PULLTYPE PULLDOWN [get_ports {GPIO_LED[6]}]
set_property PULLTYPE PULLDOWN [get_ports {GPIO_LED[7]}]
set_property PULLTYPE PULLDOWN [get_ports {GPIO_LED[8]}]
set_property PULLTYPE PULLDOWN [get_ports {GPIO_LED[9]}]
set_property PULLTYPE PULLUP [get_ports {GPIO_DIP_SW[0]}]
set_property PULLTYPE PULLUP [get_ports {GPIO_DIP_SW[1]}]
set_property PULLTYPE PULLUP [get_ports {GPIO_DIP_SW[2]}]
set_property PULLTYPE PULLDOWN [get_ports {GPIO_DIP_SW[3]}]
set_property PULLTYPE PULLDOWN [get_ports {GPIO_DIP_SW[4]}]
set_property PULLTYPE PULLDOWN [get_ports {GPIO_DIP_SW[5]}]
set_property PULLTYPE PULLDOWN [get_ports {GPIO_DIP_SW[6]}]
set_property PULLTYPE PULLDOWN [get_ports {GPIO_DIP_SW[7]}]

set_property PACKAGE_PIN Y7 [get_ports SFPXG_MGT_CLK0_P]

set_property PACKAGE_PIN T24 [get_ports SYSCLK_100MP_IN]
set_property IOSTANDARD LVDS [get_ports SYSCLK_100MP_IN]

set_property LOC GTYE4_CHANNEL_X0Y8 [get_cells {xxv_ethernet_0/inst/i_xxv_ethernet_0_gt/inst/gen_gtwizard_gtye4_top.xxv_ethernet_0_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_channel_container[2].gen_enabled_channel.gtye4_channel_wrapper_inst/channel_inst/gtye4_channel_gen.gen_gtye4_channel_inst[0].GTYE4_CHANNEL_PRIM_INST}]
set_property PACKAGE_PIN M2 [get_ports SFP1_RX_P]
set_property PACKAGE_PIN M1 [get_ports SFP1_RX_N]
set_property PACKAGE_PIN N5 [get_ports SFP1_TX_P]
set_property PACKAGE_PIN N4 [get_ports SFP1_TX_N]
set_property PACKAGE_PIN D13 [get_ports {SFP1_RATE_SELECT[0]}]
set_property PACKAGE_PIN E12 [get_ports {SFP1_RATE_SELECT[1]}]
set_property PACKAGE_PIN C13 [get_ports SFP1_TDIS]

set_property IOSTANDARD LVCMOS33 [get_ports {SFP1_RATE_SELECT[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SFP1_RATE_SELECT[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports SFP1_TDIS]

set_property PACKAGE_PIN H13 [get_ports GPIO_SW5_EXP]
set_property IOSTANDARD LVCMOS33 [get_ports GPIO_SW5_EXP]
set_property PULLTYPE PULLDOWN [get_ports GPIO_SW5_EXP]

set_property IOSTANDARD LVCMOS33 [get_ports GPIO_SW4_EXP]
set_property PACKAGE_PIN J13 [get_ports GPIO_SW4_EXP]
set_property PULLTYPE PULLDOWN [get_ports GPIO_SW4_EXP]

set_property PACKAGE_PIN H12 [get_ports GPIO_SW3_EXP]
set_property IOSTANDARD LVCMOS33 [get_ports GPIO_SW3_EXP]
set_property PULLTYPE PULLDOWN [get_ports GPIO_SW3_EXP]

set_property PACKAGE_PIN J12 [get_ports GPIO_SW2_EXP]
set_property IOSTANDARD LVCMOS33 [get_ports GPIO_SW2_EXP]
set_property PULLTYPE PULLDOWN [get_ports GPIO_SW2_EXP]

set_property PACKAGE_PIN AD15 [get_ports EEPROM_DO]
set_property IOSTANDARD LVCMOS33 [get_ports EEPROM_DO]

set_property PACKAGE_PIN W16 [get_ports EEPROM_DI]
set_property IOSTANDARD LVCMOS33 [get_ports EEPROM_DI]

set_property PACKAGE_PIN AD13 [get_ports EEPROM_SK]
set_property IOSTANDARD LVCMOS33 [get_ports EEPROM_SK]

set_property PACKAGE_PIN AD14 [get_ports EEPROM_CS]
set_property IOSTANDARD LVCMOS33 [get_ports EEPROM_CS]

set_false_path -from [get_ports GPIO_SW5_EXP]
set_false_path -from [get_ports GPIO_SW4_EXP]
set_false_path -from [get_ports GPIO_SW3_EXP]
set_false_path -from [get_ports GPIO_SW2_EXP]
set_false_path -from [get_ports GPIO_DIP_SW*]
set_false_path -to [get_ports GPIO_LED*]
set_false_path -to [get_ports SFP1_TDIS]

set_max_delay -datapath_only -from [get_clocks SFPXG_MGT_CLK0_P] -to [get_clocks clk_out1_clk_wiz_0] 4.000
set_max_delay -datapath_only -from [get_clocks clk_out1_clk_wiz_0] -to [get_clocks {txoutclk_out[0]}] 4.000
set_max_delay -datapath_only -from [get_clocks {txoutclk_out[0]}] -to [get_clocks clk_out1_clk_wiz_0] 4.000

set_property BITSTREAM.CONFIG.EXTMASTERCCLK_EN disable [current_design]
set_property CONFIG_MODE SPIx4 [current_design]
set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]
set_property BITSTREAM.CONFIG.SPI_FALL_EDGE YES [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE 102.0 [current_design]
